### ISSUE TITLE
I'd like to add info to FAQs. Opinions?

### ISSUE THREAD

**Issue by cmavr8** [openLRSng/openLRSngWiki#3]
I would like to add some info to the FAQs. Do you think the FAQs are ok, or should new pages be created?

The content I want to add is:
- A slightly modified (change of language?) version of this http://rc.velvetnut.com/index.php?title=Troubleshooting_range_issues
- "How to measure performance", based on this post http://www.rcgroups.com/forums/showpost.php?p=31479778&postcount=7210
- Some notes about spectrum analyzer usage, copy from here http://rc.velvetnut.com/index.php?title=Spectrum_analyzer
- reference tests, but after some cleaning-up http://rc.velvetnut.com/index.php?title=Reference_performance_of_OpenLRS_setups

Now that I look at the list, maybe it would be better to start a wiki article dedicated to performance/range?

**Comment by JohnieBraaf** [comment]
Sounds like a great idea to me. 

Please also have a look at the doc branch I created, it's an attempt to streamline the wiki.

**Comment by cmavr8** [comment]
Thanks for the branch pointer. That's what I've been wanting for a while :) 
I'll feel free to fork and PR, so we can discuss the specifics there, before merging.
