### ISSUE TITLE
The "RF Power" setting on the transmitter

### ISSUE THREAD

**Issue by kcleung** [openLRSng/openLRSngWiki#6]
In the wiki:

https://github.com/openLRSng/openLRSngWiki/wiki/Settings-Guide

the "RF Power" is said to be from a scale of 0-7

Then the wiki says that the scale is "not linear", 

So is it exponential?

and then the wiki says "for 1W device should not be set to 0"

I have the following questions:
- Suppose if I buy a OrangeRx 1W transmitter, and a OrangeRx 100mW receiver, then will the transmission power be automatically limited to 100mW?
- On a 1W transmitter, if I set the "RF power" to "0", then how much power will this translate to?  
- If I want the output power to be 25mW or 100mW, how should I set the "RF power" accordingly in each case?

**Comment by kh4** [comment]
For 100mW module:
7=100mW 6=50mW 5=25mW 4=13mW 3=6mW 2=3mW 1=1.6mW 0=1.3mW

For 1W module @5V (Hawkeye/DTF gear)
7=800mW 6=650mW 5=550mW 4...0 undefined

1W  @ 3v3 (OrangeRX/Flytron)
7=600mW 6=500mW 5=400mW 4..0 undefined

The lower power levels on RFM23BP are not defined in datasheet and they may be unreliable. I have seen an 1W module outputting virtually nothing (<1mW) on powerlevels 0 and 1.

**Comment by kh4** [comment]
Added table to wiki
