### ISSUE TITLE
openlrs-m3 1W  Write??

### ISSUE THREAD

**Issue by wcq12** [openLRSng/openLRSngWiki#8]
Hi, I am an electronic fan from China and I like open source projects!

I changed the OPENLRS-M3 OPENLRS project schematic, PCB, using OPENLRS-M3 and Openlrs_rx V2, I use rfm23bp vcc = 5.5 v, there is a problem:
## RF output power is very low, about 5 meters out of control, I do not know why?
I have replaced 2PCS rfm23bp module problem still can not solve
I have changed many versions of the firmware.
My firmware version is 3.8.8
I ask for help
BY: BH4QLF
Thank you!
[openlrs-m3.zip](https://github.com/openLRSng/openLRSngWiki/files/1778216/openlrs-m3.zip)

**Comment by jack113113** [comment]
check 2 pin TX- RX of modul rfm23bp, maybe you confuse it then damage modul .Or you bought wrong modul , have not version 433mhz

**Comment by fiveangle** [comment]
This issue tracker is for problems with the openLRSngWiki.  Please post issues with openLRSng on the main project tracker: https://github.com/openLRSng/openLRSng/issues

Thanks,

-=dave
