### ISSUE TITLE
SBUS

### ISSUE THREAD

**Issue by mric3412** [openLRSng/openLRSngWiki#9]
Instructions to obtain SBUS on the receiver seem to be incomplete :
- Missing information about the corresponding Tx baudrate (options SBUS and SUMD in the list of Tx baudrate are not explained)
- Missing information about the required configuration of the radio transmitter : an example of the correct config with a Taranis will be great (extern RF module with PPM protocol and 16 channels maybe OK for using SBUS....?)
PS : I tested SBUS (pin13 of "wolfbox" rx with openlrsng 3.8.8) with a PixhawkLite (F427) on arduplane v3.9.3 without success. But SBUS woks with a FrSky X8R rx. However both SBUS signal (X8R and openlrsng) should be inverted. So, why does it not work with openlrsng ?...

**Comment by fiveangle** [comment]
@mric3412 - Please submit PR with proposed changes for review.  Not sure on "wolfbox" vs pixhawklite.  Would be best to post question to the main OpenLRSng issue tracker.

Thanks,

-=dave

**Comment by mikeller** [comment]
@fiveangle: The problem is that the documentation is in the wiki of this project, and there is no easy way to open pull requests for changes (and public editing is also locked down). Not sure why this is set up the way it is, and reluctant to change it without knowing the reasons.

**Comment by JohnieBraaf** [comment]
There was an attempt by me to convert it to documents in the source tree. See the documents branch. It's only a little behind on the wiki now.

**Comment by mikeller** [comment]
@JohnieBraaf: Ha, interesting. I was expecting to see a copy of the wiki in the repository, but I only looked in `master`. How did you convert it?

There are ways to 'link up' the repository that the wiki is backed on to a 'real' repository that can support pull requests (see https://www.growingwiththeweb.com/2016/07/enabling-pull-requests-on-github-wikis.html). I am thinking we should do that with this repository, and then start accepting pull requests for changes into the repository, and push them into the wiki once accepted.

Thoughts?

**Comment by mikeller** [comment]
@mric3412: Aand we are open for business. You can submit a pull request for your proposed changes against the documentation in this repository now.
